### ISSUE TITLE
Switch "wallet signature popup" and "missing title message"

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/desci-framework#152]
## 🚀 Feature Request

Check if title of proposal is missing before making me sign the transaction of the proposal. 

## 🔈 Motivation

Waste of time.

**Comment by Caceresenzo** [comment]
Switching wallet can only be done via metamask, I don't have any control with the code.

**Comment by Caceresenzo** [comment]
Sorry I misunderstood

**Comment by Caceresenzo** [comment]
https://github.com/crunchdao/desci/commit/3e9308ed41d7455cd8b5814ee606df71ddef6970
