### ISSUE TITLE
Control s for rerendering

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/desci-framework#154]
## 🚀 Feature Request

In the spirit of building on Overleaf, I would like to edit the markdown and, in order to re-render, both click on the re-render botton and, more easily, use the shortcut Ctrl+s.

**Comment by Caceresenzo** [comment]
`CTRL+S` is normally used for saving things, don't you think it will be a little bit confusing?

**Comment by matteoettam09** [comment]
I think not: in Overleaf ```CTRL+S``` compiles. Also, in our context in order to save you have to add a message to the saved version, so we cannot use the shortcut to save. It's a win-win to me

**Comment by Caceresenzo** [comment]
https://github.com/crunchdao/desci/commit/381b3939a9b206b247f01e9aed8cb228da2967e2
