### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/desci-framework#158]
## 🚀 Feature Request

Inside your organization (like in github, the owner of the organization needs to give you rights to be part of it), you can add a paper.
Click on "add a new paper". This has to be more straightforward than the "add your institution". @Caceresenzo, up to you to decide the process. Should they send you the github repo URL?

**Comment by Caceresenzo** [comment]
https://github.com/crunchdao/desci/commit/803a850aebbf5ba23aadf48491be3208a0c43b7f
